version: "3.5"
networks:
  default:
    name: zkevm

services:
  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ports:
      - 5432:5432
    volumes:
      - ./db/single_db_server.sql:/docker-entrypoint-initdb.d/init.sql
      - zkevm_state_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cdk_user
      - POSTGRES_PASSWORD=cdk_password
      - POSTGRES_DB=postgres
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:v3.0.2
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-node:
    container_name: zkevm-node
    image: cpucorecore/cdk-env
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    ports:
      - 9091:9091 # for metrics
      - 6060:6060
      - 8123:8123 # for rpc
      - 8133:8133 # for rpc
      - 50081:50081 # for aggregator
    volumes:
      - ./config/account.key:/app/account.key
      - ./config/node-config.toml:/app/node-config.toml
      - ./config/genesis.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/node-config.toml --components sequencer --components sequence-sender --components rpc --components aggregator --components synchronizer --components eth-tx-manager --components l2gaspricer"

  zkevm-bridge-service:
    container_name: zkevm-bridge-service
    image: cpucorecore/cdk-env
    depends_on:
      - zkevm-node
      - zkevm-state-db
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./config/account.key:/app/account.key
      - ./config/bridge-config.toml:/app/bridge-config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/bridge-config.toml"

  zkevm-data-availability:
    container_name: zkevm-data-availability
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    image: cpucorecore/cdk-env
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8444:8444
    volumes:
      - ./config/dac-config.toml:/app/dac-config.toml
      - ./config/account.key:/app/account.key
    command:
      - "/bin/sh"
      - "-c"
      - "/app/cdk-data-availability run --cfg /app/dac-config.toml"

volumes:
  deploy-zkevm_state_db_data:
