[Log]
Level = "info"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "cdk_user"
Name = "bridge_db"
Password = "cdk_password"
Host = "zkevm-state-db"
Port = "5432"
MaxConns = 20

[Etherman]
L1URL = "https://sepolia.infura.io/v3/b27a8be73bcb4bc7a83aada13c65e135"
L2URLs = ["http://zkevm-node:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
	# Read only
	[BridgeServer.DB]
	Database = "postgres"
	User = "cdk_user"
	Name = "bridge_db"
	Password = "cdk_password"
	Host = "zkevm-state-db"
	Port = "5432"
	MaxConns = 20

[NetworkConfig]
GenBlockNumber = "5098088"
PolygonZkEVMAddress = "0x52C8f9808246eF2ce992c0e1f04fa54ec3378dD1"
PolygonBridgeAddress = "0x24F2aF81Ae588690C9752A342d7549f58133CE4e"
PolygonZkEVMGlobalExitRootAddress = "0xE3A721c20B30213FEC306dd60f6c7F2fCB8b46D2"
MaticTokenAddress = "0xd76B50509c1693C7BA35514103a0A156Ca57980c"
L2PolygonBridgeAddresses = ["0x24F2aF81Ae588690C9752A342d7549f58133CE4e"]
L1ChainID = 11155111

[ClaimTxManager]
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/app/account.key", Password = "testonly"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10
