[Log]
Level = "info"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "cdk_user"
Name = "bridge_db"
Password = "cdk_password"
Host = "zkevm-state-db"
Port = "5432"
MaxConns = 20

[Etherman]
L1URL = "http://host.docker.internal:8545"
L2URLs = ["http://zkevm-node:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"

[BridgeServer.DB]
Database = "postgres"
User = "cdk_user"
Name = "bridge_db"
Password = "cdk_password"
Host = "zkevm-state-db"
Port = "5432"
MaxConns = 20

[NetworkConfig]
GenBlockNumber = "114103"
PolygonZkEVMAddress = "0xad87043eb9436b7835C66685C4DF95046a2a619b"
PolygonBridgeAddress = "0x4349D6dEc11b322d1b2823Df32d25ae4c28f3710"
PolygonZkEVMGlobalExitRootAddress = "0x8C7384132C88a26FF11d0d264253d66A9E0129dd"
MaticTokenAddress = "0x8A71f49D8eaf65c022E1Ff6b2025eAc4eBEE53C1"
L2PolygonBridgeAddresses = ["0x4349D6dEc11b322d1b2823Df32d25ae4c28f3710"]
L1ChainID = 1337

[ClaimTxManager]
FrequencyToMonitorTxs = "1s"
Enabled = true
RetryInterval = "1s"
RetryNumber = 10

[ClaimTxManager.PrivateKey]
Path = "/app/account.key"
Password = "testonly"
