[PrivateKey]
Path = "/app/account.key"
Password = "testonly"

[L1]
WsURL = "ws://host.docker.internal:8546"
RpcURL = "http://host.docker.internal:8545"
CDKValidiumAddress = "0xad87043eb9436b7835C66685C4DF95046a2a619b"
DataCommitteeAddress = "0xc1614399dfF6A83a6444d7c79eaFC975A40fA568"
Timeout = "3m"
RetryPeriod = "5s"

[Log]
Environment = "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "cdk_user"
Password = "cdk_password"
Name = "committee_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 10

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = false

[RPC.WebSockets]
Enabled = false
